### ISSUE TITLE
Broken "KlokanTech Noto Sans CJK Regular" font

### ISSUE THREAD

**Issue by eogurtsov** [klokantech/klokantech-gl-fonts#1]
Please fix broken "KlokanTech Noto Sans CJK Regular" font.

**Comment by klokan** [comment]
Incorrect bug report. No error message provided, no information about which version (TTF/PBF) or which characters are problem and what software do you use the font in. As a result it is not possible to reproduce the issue.

The font displays Chinese, Japanese and Korean characters correctly at http://maps.klokantech.com/. It is not broken.

Please - create a new ticket - with clear title and reproducible bug report.

**Comment by eogurtsov** [comment]
Problem with KlokanTechNotoSansCJK-Regular.otf but all ok with KlokanTechNotoSans-Regular.ttf or KlokanTechNotoSansCJK-Bold.otf
